### ISSUE TITLE
Wiremock client can't connect to server over proxy.

### ISSUE THREAD

**Issue by jaceko** [tomakehurst/wiremock#657]
We have a standalone Wiremock server in a test environment which is available only via http proxy.
I'd be good to if the wiremock client had configurable http proxy. 
e.g.
`Wiremock.configureFor("wiremock_server_remote", 8080, new ProxySettings("proxy_server", proxyPort));`

**Comment by tomakehurst** [comment]
Would this work for you?
https://github.com/tomakehurst/wiremock/pull/636

**Comment by maheshsubramanian** [comment]
@jaceko: I think the above merge should work for us...

**Comment by tomakehurst** [comment]
Cool. I've merged it. Will release once I've got one or two other bits added.

**Comment by phani-kaliginadi** [comment]
Hi @tomakehurst : is this change in 2.6.0 yet? 
we are also looking for exactly for this feature. All our hosts behind Socks proxy including wiremock server. I just upgraded to latest 2.6.0. But still not seeing the proxy feature.

**Comment by tomakehurst** [comment]
No, it'll be in the next release.
